# Generated by Django 6.0 on 2025-12-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolom_1', models.CharField(max_length=100)),
                ('kolom_2', models.CharField(max_length=100)),
                ('kolom_3', models.CharField(max_length=100)),
                ('kolom_4', models.CharField(max_length=100)),
                ('kolom_5', models.CharField(max_length=100)),
                ('kolom_6', models.CharField(max_length=100)),
                ('kolom_7', models.CharField(max_length=100)),
                ('kolom_8', models.CharField(max_length=100)),
                ('kolom_9', models.CharField(max_length=100)),
                ('kolom_10', models.CharField(max_length=100)),
                ('kolom_11', models.CharField(max_length=100)),
                ('kolom_12', models.CharField(max_length=100)),
                ('kolom_13', models.CharField(max_length=100)),
            ],
        ),
    ]
