# Generated by Django 6.0 on 2025-12-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_datalaporan_kolom_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalaporan',
            name='tahun',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_1',
            field=models.CharField(max_length=100, verbose_name='Nama Siswa'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_10',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='September'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_11',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='Oktober'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_12',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='November'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_13',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='Desember'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_2',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='Januari'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_3',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='Februari'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_4',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='Maret'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_5',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='April'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_6',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='Mei'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_7',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='Juni'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_8',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='Juli'),
        ),
        migrations.AlterField(
            model_name='datalaporan',
            name='kolom_9',
            field=models.CharField(blank=True, choices=[('', 'None'), ('Sudah', 'Sudah'), ('Belum', 'Belum')], default='', max_length=10, null=True, verbose_name='Agustus'),
        ),
    ]
